---
baseURL: https://www.juanvillela.dev
title: Juan Villela
languageCode: en-us
enableRobotsTXT: true
publishdir: dist
metaDataFormat: yaml
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]
enableEmoji: true
canonifyURLs: true

outputs:
  home: ['html']

params:
  meta:
    description: Freelance Front-End Developer, automation nerd, and Florida man.
    author: Juan Villela
    social: fourjuaneight
    theme: '#9580ff'
