---
baseURL: https://juanvillela.dev
title: Juan Villela
languageCode: en-us
enableRobotsTXT: true
publishdir: dist
metaDataFormat: yaml
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]
enableEmoji: true
canonifyURLs: true

security:
  enableInlineShortcodes: false
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^babel$"]

outputs:
  home: ['html']

sitemap:
  disable: true

params:
  meta:
    description: Coder, automation nerd, and amateur archivist.
    author: Juan Villela
    social: fourjuaneight
    theme: '#9580ff'
