version: '3'
services:
  finserv-glance-dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '1313:1313'
    entrypoint: npm start
  finserv-glance-prod:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    entrypoint: npm run build:serve
