[build]
  command = "npm run build:prod"
  publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.87.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.87.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.87.0"

[[redirects]]
  from = "/about/"
  to = "https://www.cleverlaziness.com/about/"
  force = true

[[redirects]]
  from = "/posts/"
  to = "https://www.cleverlaziness.com/posts/"
  force = true

[[redirects]]
  from = "/microblog/"
  to = "https://www.cleverlaziness.com/microblog/"
  force = true

[[redirects]]
  from = "/posts/comfort-zone/"
  to = "https://www.cleverlaziness.com/posts/"
  force = true

[[redirects]]
  from = "/posts/on-struggle/"
  to = "https://www.cleverlaziness.com/posts/"
  force = true

[[redirects]]
  from = "/posts/february-notes/"
  to = "https://www.cleverlaziness.com/posts/february-notes/"
  force = true

[[redirects]]
  from = "/posts/january-notes/"
  to = "https://www.cleverlaziness.com/posts/january-notes/"
  force = true

[[redirects]]
  from = "/posts/march-notes/"
  to = "https://www.cleverlaziness.com/posts/march-notes/"
  force = true

[[redirects]]
  from = "/posts/procastinating/"
  to = "https://www.cleverlaziness.com/posts/procastinating/"
  force = true

[[redirects]]
  from = "/posts/spreadsheets-reloaded/"
  to = "https://www.cleverlaziness.com/posts/spreadsheets-reloaded/"
  force = true

[[redirects]]
  from = "/posts/spreadsheets/"
  to = "https://www.cleverlaziness.com/posts/spreadsheets/"
  force = true

[[redirects]]
  from = "/posts/year-of-focus/"
  to = "https://www.cleverlaziness.com/posts/year-of-focus/"
  force = true

[[redirects]]
  from = "/posts/year-of-quality/"
  to = "https://www.cleverlaziness.com/posts/year-of-quality/"
  force = true
